### ISSUE TITLE
Unsafe cast will make fuzzers fail

### ISSUE THREAD

**Issue by adhusson** [MerlinEgalite/solvest#13]
Here, an unsafe cast (which is OK in all realistic contexts) may make fuzzers fail:

https://github.com/MerlinEgalite/solvest/blob/3188a59fb97b85792f31bd6320b6e9605824aff6/src/Vest.sol#L122-L124

Even if tests internal to this lib work, people who test their own stuff that depends on solvest may get surprises.

**Comment by MerlinEgalite** [comment]
What do you suggest? To safe cast?

**Comment by adhusson** [comment]
Yes!

**Comment by MerlinEgalite** [comment]
But even with safe cast it would revert earlier anyway no? So I'm not sure in fact what is the problem

**Comment by adhusson** [comment]
It would revert and alert to the problem, whereas just cast would silently mangle the values and you get a surprising error later. It is not a big deal though :D
