### ISSUE TITLE
Confused by `safeTransferFrom` in TransferVest

### ISSUE THREAD

**Issue by adhusson** [MerlinEgalite/solvest#14]
Here:

https://github.com/MerlinEgalite/solvest/blob/3188a59fb97b85792f31bd6320b6e9605824aff6/src/TransferVest.sol#L51

The ERC20 may not implement `safeTransferFrom`. Why not `transferFrom` (which is in EIP20) and wrap the transfer in a `require`?

**Comment by MerlinEgalite** [comment]
This is just a wrapper from the solmate's `safeTransferLib` around the `transferFrom` so there's no issue
