### ISSUE TITLE
No check for `id != 0` in many functions

### ISSUE THREAD

**Issue by adhusson** [MerlinEgalite/solvest#9]
Several functions will accept the id 0. It is better to add a 0 check in `_validateId` (or better: don't check `id` at all and check `vesting.receiver != address(0)`). 

It would not only match the behavior of DssVest, it would prevent can setting bits on the vesting with id 0 using `protect` for instance:

```solidity
vest.protect(0);
Vest.Vesting memory vesting = vest.getVesting(0);
assertTrue(vesting.protected); // works
```

**Comment by MerlinEgalite** [comment]
Good idea!
